image: Visual Studio 2022

clone_folder: C:\follow

environment:
  GOPATH: C:\gopath
  GOTOOLCHAIN: go1.23.0
  PATH: C:\gopath\bin;C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%

install:
  - go env
  - choco install -y make
  - make setup

before_build:
  - make lint

build_script:
  - make test

test: off

deploy: off
