image: Visual Studio 2019

clone_folder: C:\follow

environment:
  GOPATH: C:\gopath
  PATH: C:\gopath\bin;C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%
  GO: go1.19

install:
  - go install golang.org/dl/%GO%@latest
  - '%GO% download'
  - go env

  - choco install -y make
  - make setup

before_build:
  - make lint vet

build_script:
  - make test

test: off

deploy: off
