version: 2.1

orbs:
  go: circleci/go@1.7.0

workflows:
  standard:
    jobs:
    - test

jobs:
  test:
    executor:
      name: go/default
      tag: '1.17'
    steps:
      - checkout
      - printenv
      - go/load-cache
      - go/mod-download
      - run: make setup
      - go/save-cache
      - lint
      - run: make test

commands:
  printenv:
    steps:
    - run: go version
    - run: go env

  lint:
    steps:
    - restore_cache:
        key: lint-v1-{{ .Revision }}
    - run: ls .circleci/lintok > /dev/null 2>&1 || make vet lint && touch .circleci/lintok
    - save_cache:
        key: lint-v1-{{ .Revision }}
        paths:
        - .circleci/lintok
